const fs = require("fs");
const path = "C:/workspace/ai-agent/web/src/main.jsx";

const content = [
'import React, { useEffect, useMemo, useState } from "react";',
'import { createRoot } from "react-dom/client";',
'import {',
'  Bot, BrainCircuit, Cable, ChevronDown, ChevronRight, Database,',
'  KeyRound, Library, LogOut, MessageSquare, Palette, Plus, RefreshCcw,',
'  Send, ShieldCheck, Sparkles, Trash2, Upload, Users, Settings, Wrench',
'} from "lucide-react";',
'import "./styles.css";',
"import { MessageRenderer } from './components';",
'',
'const TOKEN_KEY = "agent-platform-token";',
'const THEME_KEY = "agent-platform-theme";',
'const THEMES = [',
'  { id: "dark", label: "暗黑默认", icon: "\\ud83c\\udf11" },',
'  { id: "ice", label: "冰晶色", icon: "\\u2744\\ufe0f" },',
'  { id: "planet", label: "悬浮星体", icon: "\\ud83c\\udf10" }',
'];',
'',
'function authHeaders(token) {',
'  return { "Content-Type": "application/json", Authorization: `Bearer ${token}` };',
'}',
'',
'async function api(path, { token, method = "GET", body } = {}) {',
'  const response = await fetch(path, {',
'    method, headers: token ? authHeaders(token) : { "Content-Type": "application/json" },',
'    body: body ? JSON.stringify(body) : undefined',
'  });',
'  const data = response.status === 204 ? null : await response.json();',
'  if (!response.ok) { throw new Error(data?.detail || "Request failed"); }',
'  return data;',
'}',
'',
'function TreeNode({ node, depth = 0, expandedIds, onToggle, onSelect, selectedId }) {',
'  const isExpanded = expandedIds.has(node.id);',
'  const isSelected = selectedId === node.id;',
'  return (',
'    <div>',
'      <div className="tree-node" style={{ paddingLeft: depth * 20 + 8 }}',
'           onClick={() => onSelect && onSelect(node.id)}>',
'        <button className="tree-toggle"',
'          onClick={(e) => { e.stopPropagation(); onToggle(node.id); }}',
'          style={{ visibility: node.children.length ? "visible" : "hidden" }}>',
'          {isExpanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}',
'        </button>',
'        <Library size={14} style={{ marginRight: 6, color: isSelected ? "#5de2b9" : "#9ea49b" }} />',
'        <span style={{ fontWeight: isSelected ? 700 : 400 }}>{node.name}</span>',
'        {node.document_count > 0 && (',
'          <span style={{ marginLeft: 6, fontSize: 11, color: "#6a7098" }}>({node.document_count})</span>',
'        )}',
'      </div>',
'      {isExpanded && node.children.map(child => (',
'        <TreeNode key={child.id} node={child} depth={depth + 1} expandedIds={expandedIds}',
'          onToggle={onToggle} onSelect={onSelect} selectedId={selectedId} />',
'      ))}',
'    </div>',
'  );',
'}',
].join("\\n");

fs.writeFileSync(path, content, "utf8");
console.log("Phase 1 written:", content.length, "chars");